package com.atypon.nosql;

public enum DatabaseOperation {
    ADD_DOCUMENT,
    READ_DOCUMENTS,
    REMOVE_DOCUMENTS,
    UPDATE_DOCUMENTS,
    CREATE_DATABASE,
    REMOVE_DATABASE,
    CREATE_COLLECTION,
    REMOVE_COLLECTION,
    CREATE_INDEX,
    REMOVE_INDEX
}
