package com.atypon.nosql.databaserequest;

public enum DatabaseOperation {
    ADD_DOCUMENT,
    READ_DOCUMENTS,
    REMOVE_DOCUMENTS,
    UPDATE_DOCUMENTS,
    CREATE_DATABASE,
    REMOVE_DATABASE,
    GET_DATABASES,
    CREATE_COLLECTION,
    REMOVE_COLLECTION,
    GET_COLLECTIONS,
    CREATE_INDEX,
    REMOVE_INDEX,
    GET_INDEXES
}
